### ISSUE TITLE
Create a logo for the app

### ISSUE THREAD

**Issue by anshulhq** [ACM-VIT/Paint-me#6]
Make a simple logo for the PaintMe app and upload it on the pics folder!

**Comment by SaxenaAnushka102** [comment]
Hello Anshul!
I'd like to contribute. Can you please assign the issue to me?

**Comment by anshulhq** [comment]
Hey SaxenaAnushka102!
This issue has been assigned to you! Good luck!

**Comment by yugalibalbudhe** [comment]
Hey @anshul-kr1 I've just uploaded one logo for your app. Do check it! And let me know if any changes are required.

**Comment by anshulhq** [comment]
Hello @yugalibalbudhe , the task was already assigned to @SaxenaAnushka102 , I'm sorry but I can't accept your contribution without you asking to be assigned the work. Read the Readme for all the details on how to contribute!

**Comment by SaxenaAnushka102** [comment]
Hey @anshul-kr1 I'm on it! Could you please provide the required picture resolution & dimension details?

**Comment by anshulhq** [comment]
hey! Final size should be 512px x 512px. Format:  PNG. Make sure you upload a high res version of your logo as well since it will then be used in the Splash Screen of the app as a contribution. Upload it on the pics folder, Good to hear that you're working on it!

**Comment by yugalibalbudhe** [comment]
But I've actually contributed na 🥲
So it should be my contribution only.
Did you like the logo?

**Comment by anshulhq** [comment]
Hey @yugalibalbudhe , I can't see any Pull requests from you.
